[package]
name = "pomprt"
version = "0.1.0"
authors = ["Rini"]
edition = "2021"
description = "a tiny prompt library"
repository = "https://codeberg.org/rini/nwn"
license = "Apache-2.0"
publish = false

[profile.release]
strip = true
lto = true

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.147"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.3.9"
