[package]
name = "pomprt"
version = "0.1.0"
authors = ["Rini"]
edition = "2021"
description = "a tiny prompt library"
repository = "https://codeberg.org/rini/nwn"
license = "Apache-2.0"
publish = false

[profile.release]
strip = true
lto = true

[target.'cfg(unix)'.dependencies]
libc = "0.2.147"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [
    "consoleapi",
    "processenv",
    "winbase",
] }

[dependencies]
winapi = { version = "0.3.9", features = ["handleapi"] }
